export const IMAGES_PER_ROW = 6;
export const IMAGES_PER_COLUMN = 6;

export const SHEET_WIDTH = 2694;
export const SHEET_HEIGHT = 4206;
export const CARD_WIDTH = SHEET_WIDTH / IMAGES_PER_COLUMN;
export const CARD_HEIGHT = SHEET_HEIGHT / IMAGES_PER_ROW;

export const MARKET_PADDING_TOP = 153;
export const MARKET_PADDING_BOTTOM = 45;
export const MARKET_PADDING_LEFT = 45;
export const MARKET_PADDING_RIGHT = 45;
export const MARKET_ITEM_MARGIN = 95;
export const MARKET_WIDTH = 2717;
export const MARKET_HEIGHT = 906;

export const S_SCALE = 0.37;

export const SHEET_WIDTH_S = S_SCALE * SHEET_WIDTH;
export const SHEET_HEIGHT_S = S_SCALE * SHEET_HEIGHT;
export const CARD_WIDTH_S = S_SCALE * CARD_WIDTH;
export const CARD_HEIGHT_S = S_SCALE * CARD_HEIGHT;

export const MARKET_PADDING_TOP_S = S_SCALE * MARKET_PADDING_TOP;
export const MARKET_PADDING_BOTTOM_S = S_SCALE * MARKET_PADDING_BOTTOM;
export const MARKET_PADDING_LEFT_S = S_SCALE * MARKET_PADDING_LEFT;
export const MARKET_PADDING_RIGHT_S = S_SCALE * MARKET_PADDING_RIGHT;
export const MARKET_ITEM_MARGIN_S = S_SCALE * MARKET_ITEM_MARGIN;
export const MARKET_WIDTH_S = S_SCALE * MARKET_WIDTH;
export const MARKET_HEIGHT_S = S_SCALE * MARKET_HEIGHT;
